Description: CF Stack for the Penny Discord Bot Deployment

Parameters:
  BotToken:
    Type: String
    Description: The private token of the Penny-Bot
  ApiGatewayEndpoint:
    Type: String
    Description: The endpoint url of the api gateway
  RepositoryName:
    Type: String
    Description: The name of the ECR repository
    Default: penny-bot-discord-image

Resources:
  botAppRunner:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: Penny-Bot  
      HealthCheckConfiguration:
        HealthyThreshold: 2
        Interval: 5
        Path: /
        Timeout: 2
        UnhealthyThreshold: 2
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:user/penny-bot-deployer
        AutoDeploymentsEnabled: true
        ImageRepository:
          #ImageIdentifier: !GetAtt botECRRepository.RepositoryUri
          ImageIdentifier: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}:latest
          ImageRepositoryType: ECR
          ImageConfiguration:
            StartCommand: docker run -p 8080:8080 177420307256.dkr.ecr.eu-west-1.amazonaws.com/penny-bot-discord-image
            Port: 8080
            RuntimeEnvironmentVariables:
              - 
                Name: BOT_TOKEN
                Value: !Sub ${BotToken}
              - 
                Name: API_BASE_URL
                Value: !Sub ${ApiGatewayEndpoint}