Transform: AWS::Serverless-2016-10-31
Description: CF Stack for the Penny Discord Bot

Parameters:
  apiGatewayName:
    Type: String
    Default: penny-bot-api
  FileNameAddCoins:
    Type: String
    Description: Filename of the code function for the adding of coins uploaded to S3
  FileNameBot:
    Type: String
    Description: Filename of the code function for the bot uploaded to S3

Resources:
  botWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 
        Bucket: penny-bot-discord
        Key: !Sub ${FileNameBot}-webhook-lambda
      Handler: handler
      Runtime: provided.al2
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
            AllowOrigins:
                - "*"
      Role: !GetAtt lambdaIAMRole.Arn
  
  lambdaIAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow 
            Principal:
              Service: 
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
      Policies: 
        - PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchGetItem
                  - dynamodb:DeleteItem
                  - dynamodb:Attributes
                  - dynamodb:LeadingKeys
                  - dynamodb:ConditionCheckItem
                  - dynamodb:Scan
                  - lambda:UpdateFunctionCode
                Effect: Allow 
                Resource: 
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${FileNameBot}-lambda:*
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FileNameAddCoins}-lambda
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FileNameBot}-webhook-lambda
          PolicyName: lamda