name: Check cloudformation lint 

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Check cloudformation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup cloudformation lint
      uses: ScottBrenner/cfn-lint-action@v2.2.1
    - name: Run cloudformation lint
      run: cfn-lint -t CODE/Stack.yml
    - name: Run serverless lint
      run: cfn-lint -t CODE/ServerlessStack.yml