name: Deploy bot stack

on:
  push:
    branches:
      - main
    paths:
      - 'CODE/Stack.yml'

jobs:
  deploy: 
    name: Deploy Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Configure AWS credentials
        id: cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOYER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOYER_ACCESS_SECRET_KEY }}
          aws-region: 'eu-west-1'
      - name: Deploy to AWS cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: penny-discord-bot-stack
          template: ./CODE/Stack.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            BotToken=${{ secrets.BOT_TOKEN }}
