name: Build and upload lambda functions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and upload to S3 
    runs-on: ubuntu-latest
    steps:
    - name: Log directory
      run: ls -a
    - name: Checkout repository
      uses: actions/checkout@v3.0.0
    - name: Build and zip
      run: |
        cd ./CODE 
        ./scripts/build-and-package.sh PennyLambdaAddCoins PennyLambdaBot
    - name: Remove build file
      run: |
        cd './CODE/.build/lambda/'
        sudo rm -rf PennyLambdaAddCoins
        sudo rm -rf PennyLambdaBot
    - name: Deploy to S3
      id: s3deploy
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'penny-bot-discord'
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_ACCESS_SECRET_KEY }}
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: './CODE/.build/lambda/'
    - name: Update Lambda code
      run: |
        aws lambda update-function-code \
          --function-name 'PennyLambdaAddCoins-lambda' \
          --s3-bucket 'penny-bot-discord' \
          --s3-key 'PennyLambdaAddCoins.zip'
        aws lambda update-function-code \
          --function-name 'PennyLambdaBot-lambda' \
          --s3-bucket 'penny-bot-discord' \
          --s3-key 'PennyLambdaBot.zip'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_ACCESS_SECRET_KEY }}
        AWS_REGION: 'eu-west-2'

